# Generated by Django 3.2 on 2021-05-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_singlewordanswer_singlewordquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlewordquestion',
            name='video_path',
            field=models.CharField(max_length=200),
        ),
    ]
