# Generated by Django 3.2 on 2022-08-13 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_missingwordsanswer_missingwordsquestion_singlesentenceanswer_singlesentencequestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingwordsanswer',
            name='text',
        ),
    ]
