# Generated by Django 3.2 on 2021-06-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipquiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoquiz',
            name='is_visible',
            field=models.BooleanField(default=False, help_text='Whether the quiz is visible or not'),
        ),
    ]
